// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.0--rc1
// source: playerinfo.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	cproto "mmo/messages/cproto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家数据序列化存档
type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base       *BaseInfo          `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Cards      []*cproto.CharCard `protobuf:"bytes,2,rep,name=Cards,proto3" json:"Cards,omitempty"`
	NextCardId int32              `protobuf:"varint,3,opt,name=NextCardId,proto3" json:"NextCardId,omitempty"`
	DaySign    *DaySign           `protobuf:"bytes,4,opt,name=DaySign,proto3" json:"DaySign,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetBase() *BaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PlayerInfo) GetCards() []*cproto.CharCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *PlayerInfo) GetNextCardId() int32 {
	if x != nil {
		return x.NextCardId
	}
	return 0
}

func (x *PlayerInfo) GetDaySign() *DaySign {
	if x != nil {
		return x.DaySign
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId int32 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Uid   int32 `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Stack int32 `protobuf:"varint,3,opt,name=Stack,proto3" json:"Stack,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *Item) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Item) GetStack() int32 {
	if x != nil {
		return x.Stack
	}
	return 0
}

type Vector3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{2}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ScenePos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId uint64   `protobuf:"varint,1,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	CfgId   int32    `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Token   int32    `protobuf:"varint,3,opt,name=Token,proto3" json:"Token,omitempty"`
	Pos     *Vector3 `protobuf:"bytes,4,opt,name=Pos,proto3" json:"Pos,omitempty"`
}

func (x *ScenePos) Reset() {
	*x = ScenePos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScenePos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenePos) ProtoMessage() {}

func (x *ScenePos) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenePos.ProtoReflect.Descriptor instead.
func (*ScenePos) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{3}
}

func (x *ScenePos) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *ScenePos) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ScenePos) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *ScenePos) GetPos() *Vector3 {
	if x != nil {
		return x.Pos
	}
	return nil
}

type BaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId        int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"` // uid，存储的key
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level      int32  `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Exp        int64  `protobuf:"varint,4,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Money      int64  `protobuf:"varint,5,opt,name=Money,proto3" json:"Money,omitempty"`
	LoginTimes int32  `protobuf:"varint,6,opt,name=LoginTimes,proto3" json:"LoginTimes,omitempty"`
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{4}
}

func (x *BaseInfo) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *BaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BaseInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *BaseInfo) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *BaseInfo) GetLoginTimes() int32 {
	if x != nil {
		return x.LoginTimes
	}
	return 0
}

type DaySign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastDaySigned int32 `protobuf:"varint,1,opt,name=LastDaySigned,proto3" json:"LastDaySigned,omitempty"` // 上次签到的日期
}

func (x *DaySign) Reset() {
	*x = DaySign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaySign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaySign) ProtoMessage() {}

func (x *DaySign) ProtoReflect() protoreflect.Message {
	mi := &file_playerinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaySign.ProtoReflect.Descriptor instead.
func (*DaySign) Descriptor() ([]byte, []int) {
	return file_playerinfo_proto_rawDescGZIP(), []int{5}
}

func (x *DaySign) GetLastDaySigned() int32 {
	if x != nil {
		return x.LastDaySigned
	}
	return 0
}

var File_playerinfo_proto protoreflect.FileDescriptor

var file_playerinfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0a, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x65, 0x78, 0x74, 0x43,
	0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4e, 0x65, 0x78,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x44, 0x61, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x07, 0x44, 0x61, 0x79,
	0x53, 0x69, 0x67, 0x6e, 0x22, 0x44, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x22, 0x33, 0x0a, 0x07, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x59, 0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x5a, 0x22,
	0x75, 0x0a, 0x08, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x50, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x23, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x33, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x45, 0x78,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x07, 0x44, 0x61, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x44, 0x61, 0x79, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x44,
	0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6e, 0x67, 0x79, 0x6f, 0x75, 0x2f, 0x63,
	0x65, 0x6c, 0x6c, 0x32, 0x2f, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x6d,
	0x6d, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_playerinfo_proto_rawDescOnce sync.Once
	file_playerinfo_proto_rawDescData = file_playerinfo_proto_rawDesc
)

func file_playerinfo_proto_rawDescGZIP() []byte {
	file_playerinfo_proto_rawDescOnce.Do(func() {
		file_playerinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_playerinfo_proto_rawDescData)
	})
	return file_playerinfo_proto_rawDescData
}

var file_playerinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_playerinfo_proto_goTypes = []interface{}{
	(*PlayerInfo)(nil),      // 0: messages.PlayerInfo
	(*Item)(nil),            // 1: messages.Item
	(*Vector3)(nil),         // 2: messages.Vector3
	(*ScenePos)(nil),        // 3: messages.ScenePos
	(*BaseInfo)(nil),        // 4: messages.BaseInfo
	(*DaySign)(nil),         // 5: messages.DaySign
	(*cproto.CharCard)(nil), // 6: cproto.CharCard
}
var file_playerinfo_proto_depIdxs = []int32{
	4, // 0: messages.PlayerInfo.Base:type_name -> messages.BaseInfo
	6, // 1: messages.PlayerInfo.Cards:type_name -> cproto.CharCard
	5, // 2: messages.PlayerInfo.DaySign:type_name -> messages.DaySign
	2, // 3: messages.ScenePos.Pos:type_name -> messages.Vector3
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_playerinfo_proto_init() }
func file_playerinfo_proto_init() {
	if File_playerinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playerinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScenePos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playerinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaySign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playerinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playerinfo_proto_goTypes,
		DependencyIndexes: file_playerinfo_proto_depIdxs,
		MessageInfos:      file_playerinfo_proto_msgTypes,
	}.Build()
	File_playerinfo_proto = out.File
	file_playerinfo_proto_rawDesc = nil
	file_playerinfo_proto_goTypes = nil
	file_playerinfo_proto_depIdxs = nil
}
