// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.0--rc1
// source: protos.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	cproto "mmo/messages/cproto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
}

func (x *ChatHello) Reset() {
	*x = ChatHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHello) ProtoMessage() {}

func (x *ChatHello) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHello.ProtoReflect.Descriptor instead.
func (*ChatHello) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{0}
}

func (x *ChatHello) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type ChatHelloRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
}

func (x *ChatHelloRet) Reset() {
	*x = ChatHelloRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatHelloRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHelloRet) ProtoMessage() {}

func (x *ChatHelloRet) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHelloRet.ProtoReflect.Descriptor instead.
func (*ChatHelloRet) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{1}
}

func (x *ChatHelloRet) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type NormalAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *NormalAck) Reset() {
	*x = NormalAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalAck) ProtoMessage() {}

func (x *NormalAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalAck.ProtoReflect.Descriptor instead.
func (*NormalAck) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{2}
}

func (x *NormalAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NormalAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ---- login & logout ----
// db, redisservice
type DBAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *DBAuth) Reset() {
	*x = DBAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBAuth) ProtoMessage() {}

func (x *DBAuth) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBAuth.ProtoReflect.Descriptor instead.
func (*DBAuth) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{3}
}

func (x *DBAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DBAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// db, redisservice
type DBAuthAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId  int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Err  string `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *DBAuthAck) Reset() {
	*x = DBAuthAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBAuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBAuthAck) ProtoMessage() {}

func (x *DBAuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBAuthAck.ProtoReflect.Descriptor instead.
func (*DBAuthAck) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{4}
}

func (x *DBAuthAck) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *DBAuthAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DBAuthAck) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// TODO: 后续player的解析可以推迟到具体逻辑服务，这样中间传递可以省一些序列化流程
type DBLoadPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *DBLoadPlayer) Reset() {
	*x = DBLoadPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBLoadPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBLoadPlayer) ProtoMessage() {}

func (x *DBLoadPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBLoadPlayer.ProtoReflect.Descriptor instead.
func (*DBLoadPlayer) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{5}
}

func (x *DBLoadPlayer) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

type DBLoadPlayerAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId       int64       `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Info      *PlayerInfo `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	NewPlayer bool        `protobuf:"varint,3,opt,name=NewPlayer,proto3" json:"NewPlayer,omitempty"`
}

func (x *DBLoadPlayerAck) Reset() {
	*x = DBLoadPlayerAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBLoadPlayerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBLoadPlayerAck) ProtoMessage() {}

func (x *DBLoadPlayerAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBLoadPlayerAck.ProtoReflect.Descriptor instead.
func (*DBLoadPlayerAck) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{6}
}

func (x *DBLoadPlayerAck) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *DBLoadPlayerAck) GetInfo() *PlayerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *DBLoadPlayerAck) GetNewPlayer() bool {
	if x != nil {
		return x.NewPlayer
	}
	return false
}

type DBSavePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *PlayerInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *DBSavePlayer) Reset() {
	*x = DBSavePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBSavePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBSavePlayer) ProtoMessage() {}

func (x *DBSavePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBSavePlayer.ProtoReflect.Descriptor instead.
func (*DBSavePlayer) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{7}
}

func (x *DBSavePlayer) GetInfo() *PlayerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// db.redis 服务
type DBRedisInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *DBRedisInit) Reset() {
	*x = DBRedisInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBRedisInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRedisInit) ProtoMessage() {}

func (x *DBRedisInit) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRedisInit.ProtoReflect.Descriptor instead.
func (*DBRedisInit) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{8}
}

func (x *DBRedisInit) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// center
type CenterReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `protobuf:"bytes,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`  // 前端服务
	NetId    uint32 `protobuf:"varint,2,opt,name=NetId,proto3" json:"NetId,omitempty"`       // 连接id
	KickPrev bool   `protobuf:"varint,3,opt,name=KickPrev,proto3" json:"KickPrev,omitempty"` // 是否踢掉前面
	UId      int64  `protobuf:"varint,4,opt,name=UId,proto3" json:"UId,omitempty"`           //
}

func (x *CenterReqLogin) Reset() {
	*x = CenterReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CenterReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterReqLogin) ProtoMessage() {}

func (x *CenterReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterReqLogin.ProtoReflect.Descriptor instead.
func (*CenterReqLogin) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{9}
}

func (x *CenterReqLogin) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CenterReqLogin) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *CenterReqLogin) GetKickPrev() bool {
	if x != nil {
		return x.KickPrev
	}
	return false
}

func (x *CenterReqLogin) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

type CenterReqLoginAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Error       string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	IsReconnect bool   `protobuf:"varint,3,opt,name=IsReconnect,proto3" json:"IsReconnect,omitempty"` // 是否断线重连
	LogicId     string `protobuf:"bytes,4,opt,name=LogicId,proto3" json:"LogicId,omitempty"`          // 断线重连时，logicId
}

func (x *CenterReqLoginAck) Reset() {
	*x = CenterReqLoginAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CenterReqLoginAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterReqLoginAck) ProtoMessage() {}

func (x *CenterReqLoginAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterReqLoginAck.ProtoReflect.Descriptor instead.
func (*CenterReqLoginAck) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{10}
}

func (x *CenterReqLoginAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CenterReqLoginAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CenterReqLoginAck) GetIsReconnect() bool {
	if x != nil {
		return x.IsReconnect
	}
	return false
}

func (x *CenterReqLoginAck) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

type CenterOnSessionClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *CenterOnSessionClose) Reset() {
	*x = CenterOnSessionClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CenterOnSessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterOnSessionClose) ProtoMessage() {}

func (x *CenterOnSessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterOnSessionClose.ProtoReflect.Descriptor instead.
func (*CenterOnSessionClose) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{11}
}

func (x *CenterOnSessionClose) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// logic->center
// 登录完毕
type OnLogicLogined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	LogicId string `protobuf:"bytes,2,opt,name=LogicId,proto3" json:"LogicId,omitempty"`
}

func (x *OnLogicLogined) Reset() {
	*x = OnLogicLogined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnLogicLogined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLogicLogined) ProtoMessage() {}

func (x *OnLogicLogined) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLogicLogined.ProtoReflect.Descriptor instead.
func (*OnLogicLogined) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{12}
}

func (x *OnLogicLogined) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *OnLogicLogined) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

type OnLogicReOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *OnLogicReOnline) Reset() {
	*x = OnLogicReOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnLogicReOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLogicReOnline) ProtoMessage() {}

func (x *OnLogicReOnline) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLogicReOnline.ProtoReflect.Descriptor instead.
func (*OnLogicReOnline) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{13}
}

func (x *OnLogicReOnline) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// scene -> logic, logic -> center
// ack NormalAck
type ReqLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *ReqLogout) Reset() {
	*x = ReqLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogout) ProtoMessage() {}

func (x *ReqLogout) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogout.ProtoReflect.Descriptor instead.
func (*ReqLogout) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{14}
}

func (x *ReqLogout) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// scene -> logic, logic -> center
// NormalAck
type OnLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *OnLogout) Reset() {
	*x = OnLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLogout) ProtoMessage() {}

func (x *OnLogout) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLogout.ProtoReflect.Descriptor instead.
func (*OnLogout) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{15}
}

func (x *OnLogout) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// gate -> logic
// enter/reenter
type LogicLoadPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `protobuf:"bytes,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"` // 前端服务
	NetId    uint32 `protobuf:"varint,2,opt,name=NetId,proto3" json:"NetId,omitempty"`      // 连接id
	UId      int64  `protobuf:"varint,3,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *LogicLoadPlayer) Reset() {
	*x = LogicLoadPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicLoadPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicLoadPlayer) ProtoMessage() {}

func (x *LogicLoadPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicLoadPlayer.ProtoReflect.Descriptor instead.
func (*LogicLoadPlayer) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{16}
}

func (x *LogicLoadPlayer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *LogicLoadPlayer) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *LogicLoadPlayer) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

type ReqOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *ReqOffline) Reset() {
	*x = ReqOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqOffline) ProtoMessage() {}

func (x *ReqOffline) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqOffline.ProtoReflect.Descriptor instead.
func (*ReqOffline) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{17}
}

func (x *ReqOffline) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// scene -> logic
type OnLeaveScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
}

func (x *OnLeaveScene) Reset() {
	*x = OnLeaveScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnLeaveScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLeaveScene) ProtoMessage() {}

func (x *OnLeaveScene) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLeaveScene.ProtoReflect.Descriptor instead.
func (*OnLeaveScene) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{18}
}

func (x *OnLeaveScene) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *OnLeaveScene) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// 客户端离线(onSessionClose)
// center -> logic, logic -> scene
// ack: normalAck
type OnOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *OnOffline) Reset() {
	*x = OnOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOffline) ProtoMessage() {}

func (x *OnOffline) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOffline.ProtoReflect.Descriptor instead.
func (*OnOffline) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{19}
}

func (x *OnOffline) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// 断线重连
// center -> logic, logic -> scene
// ack: normalAck
type OnReOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *OnReOnline) Reset() {
	*x = OnReOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnReOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnReOnline) ProtoMessage() {}

func (x *OnReOnline) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnReOnline.ProtoReflect.Descriptor instead.
func (*OnReOnline) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{20}
}

func (x *OnReOnline) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// 请求切线
// logic -> center
// ack: NormalAck
type ReqSwitchLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *ReqSwitchLine) Reset() {
	*x = ReqSwitchLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSwitchLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSwitchLine) ProtoMessage() {}

func (x *ReqSwitchLine) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSwitchLine.ProtoReflect.Descriptor instead.
func (*ReqSwitchLine) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{21}
}

func (x *ReqSwitchLine) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

// logic -> center
type OnSwitchLineEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId  int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Succ bool  `protobuf:"varint,2,opt,name=Succ,proto3" json:"Succ,omitempty"`
}

func (x *OnSwitchLineEnd) Reset() {
	*x = OnSwitchLineEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnSwitchLineEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSwitchLineEnd) ProtoMessage() {}

func (x *OnSwitchLineEnd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSwitchLineEnd.ProtoReflect.Descriptor instead.
func (*OnSwitchLineEnd) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{22}
}

func (x *OnSwitchLineEnd) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *OnSwitchLineEnd) GetSucc() bool {
	if x != nil {
		return x.Succ
	}
	return false
}

// some -> logic
// ack: NormalAck
type LogicReqSwitchLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId         int64   `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneServer string  `protobuf:"bytes,2,opt,name=SceneServer,proto3" json:"SceneServer,omitempty"`
	SceneId     uint64  `protobuf:"varint,3,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	CfgId       int32   `protobuf:"varint,4,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Token       int32   `protobuf:"varint,5,opt,name=Token,proto3" json:"Token,omitempty"`
	PosX        float32 `protobuf:"fixed32,6,opt,name=PosX,proto3" json:"PosX,omitempty"`
	PosY        float32 `protobuf:"fixed32,7,opt,name=PosY,proto3" json:"PosY,omitempty"`
	PosZ        float32 `protobuf:"fixed32,8,opt,name=PosZ,proto3" json:"PosZ,omitempty"`
}

func (x *LogicReqSwitchLine) Reset() {
	*x = LogicReqSwitchLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicReqSwitchLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicReqSwitchLine) ProtoMessage() {}

func (x *LogicReqSwitchLine) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicReqSwitchLine.ProtoReflect.Descriptor instead.
func (*LogicReqSwitchLine) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{23}
}

func (x *LogicReqSwitchLine) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *LogicReqSwitchLine) GetSceneServer() string {
	if x != nil {
		return x.SceneServer
	}
	return ""
}

func (x *LogicReqSwitchLine) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *LogicReqSwitchLine) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *LogicReqSwitchLine) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *LogicReqSwitchLine) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *LogicReqSwitchLine) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *LogicReqSwitchLine) GetPosZ() float32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

// 战斗结果
// scene -> logic
type OnFightResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	Result  int32  `protobuf:"varint,3,opt,name=Result,proto3" json:"Result,omitempty"` // 结果
	Money   int32  `protobuf:"varint,4,opt,name=Money,proto3" json:"Money,omitempty"`   // 获取金钱
	Exp     int32  `protobuf:"varint,5,opt,name=Exp,proto3" json:"Exp,omitempty"`       // 获取经验
}

func (x *OnFightResult) Reset() {
	*x = OnFightResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnFightResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnFightResult) ProtoMessage() {}

func (x *OnFightResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnFightResult.ProtoReflect.Descriptor instead.
func (*OnFightResult) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{24}
}

func (x *OnFightResult) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *OnFightResult) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *OnFightResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *OnFightResult) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *OnFightResult) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type TestSave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *PlayerInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *TestSave) Reset() {
	*x = TestSave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSave) ProtoMessage() {}

func (x *TestSave) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSave.ProtoReflect.Descriptor instead.
func (*TestSave) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{25}
}

func (x *TestSave) GetInfo() *PlayerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// logic -> scenem
type SMAllocScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId   int64 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`     // 玩家id
	CfgId int32 `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 场景配置id
}

func (x *SMAllocScene) Reset() {
	*x = SMAllocScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMAllocScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMAllocScene) ProtoMessage() {}

func (x *SMAllocScene) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMAllocScene.ProtoReflect.Descriptor instead.
func (*SMAllocScene) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{26}
}

func (x *SMAllocScene) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *SMAllocScene) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

type SMAllocSceneAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	SceneId   uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	Token     int32  `protobuf:"varint,3,opt,name=Token,proto3" json:"Token,omitempty"`
	CfgId     int32  `protobuf:"varint,4,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
}

func (x *SMAllocSceneAck) Reset() {
	*x = SMAllocSceneAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMAllocSceneAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMAllocSceneAck) ProtoMessage() {}

func (x *SMAllocSceneAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMAllocSceneAck.ProtoReflect.Descriptor instead.
func (*SMAllocSceneAck) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{27}
}

func (x *SMAllocSceneAck) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SMAllocSceneAck) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SMAllocSceneAck) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *SMAllocSceneAck) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

// 查询当前场景列表
type SMQueryScenes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SMQueryScenes) Reset() {
	*x = SMQueryScenes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMQueryScenes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMQueryScenes) ProtoMessage() {}

func (x *SMQueryScenes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMQueryScenes.ProtoReflect.Descriptor instead.
func (*SMQueryScenes) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{28}
}

type SMAckScenes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scenes []uint64 `protobuf:"varint,1,rep,packed,name=Scenes,proto3" json:"Scenes,omitempty"`
}

func (x *SMAckScenes) Reset() {
	*x = SMAckScenes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMAckScenes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMAckScenes) ProtoMessage() {}

func (x *SMAckScenes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMAckScenes.ProtoReflect.Descriptor instead.
func (*SMAckScenes) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{29}
}

func (x *SMAckScenes) GetScenes() []uint64 {
	if x != nil {
		return x.Scenes
	}
	return nil
}

// 请求场景信息(cfgId)
// ack SMQuerySceneAck
type SMReqSceneByCfgId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId int32 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
}

func (x *SMReqSceneByCfgId) Reset() {
	*x = SMReqSceneByCfgId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMReqSceneByCfgId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMReqSceneByCfgId) ProtoMessage() {}

func (x *SMReqSceneByCfgId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMReqSceneByCfgId.ProtoReflect.Descriptor instead.
func (*SMReqSceneByCfgId) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{30}
}

func (x *SMReqSceneByCfgId) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

// 查询场景的信息
type SMQueryScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId uint64 `protobuf:"varint,1,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
}

func (x *SMQueryScene) Reset() {
	*x = SMQueryScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMQueryScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMQueryScene) ProtoMessage() {}

func (x *SMQueryScene) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMQueryScene.ProtoReflect.Descriptor instead.
func (*SMQueryScene) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{31}
}

func (x *SMQueryScene) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

type SMQuerySceneAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	SceneId   uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	Token     int32  `protobuf:"varint,3,opt,name=Token,proto3" json:"Token,omitempty"`
	CfgId     int32  `protobuf:"varint,4,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
}

func (x *SMQuerySceneAck) Reset() {
	*x = SMQuerySceneAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMQuerySceneAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMQuerySceneAck) ProtoMessage() {}

func (x *SMQuerySceneAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMQuerySceneAck.ProtoReflect.Descriptor instead.
func (*SMQuerySceneAck) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{32}
}

func (x *SMQuerySceneAck) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SMQuerySceneAck) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SMQuerySceneAck) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *SMQuerySceneAck) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

// scene -> scenem
type SMRefresh struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	SceneNum  int32  `protobuf:"varint,2,opt,name=sceneNum,proto3" json:"sceneNum,omitempty"`
}

func (x *SMRefresh) Reset() {
	*x = SMRefresh{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMRefresh) ProtoMessage() {}

func (x *SMRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMRefresh.ProtoReflect.Descriptor instead.
func (*SMRefresh) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{33}
}

func (x *SMRefresh) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SMRefresh) GetSceneNum() int32 {
	if x != nil {
		return x.SceneNum
	}
	return 0
}

type SMOnSceneEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId uint64 `protobuf:"varint,1,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
}

func (x *SMOnSceneEnd) Reset() {
	*x = SMOnSceneEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMOnSceneEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMOnSceneEnd) ProtoMessage() {}

func (x *SMOnSceneEnd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMOnSceneEnd.ProtoReflect.Descriptor instead.
func (*SMOnSceneEnd) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{34}
}

func (x *SMOnSceneEnd) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// scenem -> scene
type SAllocScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId   int32  `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	SceneId uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	Token   int32  `protobuf:"varint,3,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *SAllocScene) Reset() {
	*x = SAllocScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAllocScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAllocScene) ProtoMessage() {}

func (x *SAllocScene) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAllocScene.ProtoReflect.Descriptor instead.
func (*SAllocScene) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{35}
}

func (x *SAllocScene) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *SAllocScene) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SAllocScene) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

// logic -> scene
// enter/reenter
type SceneEnter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId        int64   `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId    uint64  `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	Token      int32   `protobuf:"varint,3,opt,name=Token,proto3" json:"Token,omitempty"`
	FrontId    string  `protobuf:"bytes,4,opt,name=FrontId,proto3" json:"FrontId,omitempty"`
	NetId      uint32  `protobuf:"varint,5,opt,name=NetId,proto3" json:"NetId,omitempty"`
	LogicId    string  `protobuf:"bytes,6,opt,name=LogicId,proto3" json:"LogicId,omitempty"`
	CfgId      int32   `protobuf:"varint,7,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	SwitchLine bool    `protobuf:"varint,8,opt,name=SwitchLine,proto3" json:"SwitchLine,omitempty"`
	PosX       float32 `protobuf:"fixed32,9,opt,name=PosX,proto3" json:"PosX,omitempty"`
	PosY       float32 `protobuf:"fixed32,10,opt,name=PosY,proto3" json:"PosY,omitempty"`
	PosZ       float32 `protobuf:"fixed32,11,opt,name=PosZ,proto3" json:"PosZ,omitempty"` // 阵容信息用单独的消息发送
}

func (x *SceneEnter) Reset() {
	*x = SceneEnter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEnter) ProtoMessage() {}

func (x *SceneEnter) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEnter.ProtoReflect.Descriptor instead.
func (*SceneEnter) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{36}
}

func (x *SceneEnter) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *SceneEnter) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SceneEnter) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *SceneEnter) GetFrontId() string {
	if x != nil {
		return x.FrontId
	}
	return ""
}

func (x *SceneEnter) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *SceneEnter) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

func (x *SceneEnter) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *SceneEnter) GetSwitchLine() bool {
	if x != nil {
		return x.SwitchLine
	}
	return false
}

func (x *SceneEnter) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *SceneEnter) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *SceneEnter) GetPosZ() float32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

// logic -> scene
// ack: NormalAck
type ChangeScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64   `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId uint64  `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	Token   int32   `protobuf:"varint,3,opt,name=Token,proto3" json:"Token,omitempty"`
	CfgId   int32   `protobuf:"varint,4,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	PosX    float32 `protobuf:"fixed32,5,opt,name=PosX,proto3" json:"PosX,omitempty"`
	PosY    float32 `protobuf:"fixed32,6,opt,name=PosY,proto3" json:"PosY,omitempty"`
	PosZ    float32 `protobuf:"fixed32,7,opt,name=PosZ,proto3" json:"PosZ,omitempty"`
}

func (x *ChangeScene) Reset() {
	*x = ChangeScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeScene) ProtoMessage() {}

func (x *ChangeScene) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeScene.ProtoReflect.Descriptor instead.
func (*ChangeScene) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{37}
}

func (x *ChangeScene) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *ChangeScene) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *ChangeScene) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *ChangeScene) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ChangeScene) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *ChangeScene) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *ChangeScene) GetPosZ() float32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

// logic -> scene
type LogicOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
}

func (x *LogicOffline) Reset() {
	*x = LogicOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicOffline) ProtoMessage() {}

func (x *LogicOffline) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicOffline.ProtoReflect.Descriptor instead.
func (*LogicOffline) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{38}
}

func (x *LogicOffline) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *LogicOffline) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// logic -> scene
type SceneLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
}

func (x *SceneLeave) Reset() {
	*x = SceneLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneLeave) ProtoMessage() {}

func (x *SceneLeave) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneLeave.ProtoReflect.Descriptor instead.
func (*SceneLeave) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{39}
}

func (x *SceneLeave) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *SceneLeave) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// scene -> logic
// 进入场景成功后二次确认，keepAlive
// ack NormalAck
type CheckPlayer2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
}

func (x *CheckPlayer2) Reset() {
	*x = CheckPlayer2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPlayer2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPlayer2) ProtoMessage() {}

func (x *CheckPlayer2) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPlayer2.ProtoReflect.Descriptor instead.
func (*CheckPlayer2) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{40}
}

func (x *CheckPlayer2) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *CheckPlayer2) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// logic -> scene
type SceneInitCardFight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64              `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	LogicId string             `protobuf:"bytes,2,opt,name=LogicId,proto3" json:"LogicId,omitempty"`
	SceneId uint64             `protobuf:"varint,3,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	Token   int32              `protobuf:"varint,4,opt,name=Token,proto3" json:"Token,omitempty"`
	Cards   []*cproto.CharCard `protobuf:"bytes,5,rep,name=Cards,proto3" json:"Cards,omitempty"`
}

func (x *SceneInitCardFight) Reset() {
	*x = SceneInitCardFight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[41]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneInitCardFight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneInitCardFight) ProtoMessage() {}

func (x *SceneInitCardFight) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[41]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneInitCardFight.ProtoReflect.Descriptor instead.
func (*SceneInitCardFight) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{41}
}

func (x *SceneInitCardFight) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *SceneInitCardFight) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

func (x *SceneInitCardFight) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SceneInitCardFight) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *SceneInitCardFight) GetCards() []*cproto.CharCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type SceneCardResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId     int64  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SceneId uint64 `protobuf:"varint,2,opt,name=SceneId,proto3" json:"SceneId,omitempty"`
	// 胜利者索引
	// 0: down 1:up
	Winner int32 `protobuf:"varint,3,opt,name=Winner,proto3" json:"Winner,omitempty"`
}

func (x *SceneCardResult) Reset() {
	*x = SceneCardResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_proto_msgTypes[42]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneCardResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneCardResult) ProtoMessage() {}

func (x *SceneCardResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[42]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneCardResult.ProtoReflect.Descriptor instead.
func (*SceneCardResult) Descriptor() ([]byte, []int) {
	return file_protos_proto_rawDescGZIP(), []int{42}
}

func (x *SceneCardResult) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *SceneCardResult) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SceneCardResult) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

var File_protos_proto protoreflect.FileDescriptor

var file_protos_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x74, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x35, 0x0a, 0x09, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x40, 0x0a, 0x06, 0x44, 0x42, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x43, 0x0a, 0x09, 0x44, 0x42, 0x41, 0x75, 0x74, 0x68, 0x41, 0x63,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x55, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x22, 0x20, 0x0a, 0x0c, 0x44, 0x42, 0x4c,
	0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x0f, 0x44,
	0x42, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x65,
	0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x4e,
	0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x0c, 0x44, 0x42, 0x53, 0x61,
	0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x44, 0x42, 0x52, 0x65, 0x64, 0x69, 0x73, 0x49, 0x6e, 0x69,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x70, 0x0a, 0x0e, 0x43,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x65, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x22, 0x79, 0x0a,
	0x11, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41,
	0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x49, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x49, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x43, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x4f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55,
	0x49, 0x64, 0x22, 0x3c, 0x0a, 0x0e, 0x4f, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49, 0x64,
	0x22, 0x23, 0x0a, 0x0f, 0x4f, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x52, 0x65, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x55, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x08, 0x4f, 0x6e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55,
	0x49, 0x64, 0x22, 0x55, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4c, 0x6f, 0x61, 0x64, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x71,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x0c, 0x4f, 0x6e, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x09, 0x4f, 0x6e, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x0a, 0x4f, 0x6e, 0x52, 0x65, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x4f, 0x6e, 0x53, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x75, 0x63, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x53, 0x75, 0x63, 0x63,
	0x22, 0xca, 0x01, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x52, 0x65, 0x71, 0x53, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73,
	0x5a, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x5a, 0x22, 0x7b, 0x0a,
	0x0d, 0x4f, 0x6e, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x78, 0x70, 0x22, 0x34, 0x0a, 0x08, 0x54, 0x65,
	0x73, 0x74, 0x53, 0x61, 0x76, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x36, 0x0a, 0x0c, 0x53, 0x4d, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0f, 0x53, 0x4d, 0x41, 0x6c,
	0x6c, 0x6f, 0x63, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x22,
	0x0f, 0x0a, 0x0d, 0x53, 0x4d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73,
	0x22, 0x25, 0x0a, 0x0b, 0x53, 0x4d, 0x41, 0x63, 0x6b, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x06, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x4d, 0x52, 0x65, 0x71,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x42, 0x79, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67,
	0x49, 0x64, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x4d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0f,
	0x53, 0x4d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x41, 0x63, 0x6b, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66,
	0x67, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x09, 0x53, 0x4d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x4d,
	0x4f, 0x6e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x0b, 0x53, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8a, 0x02, 0x0a, 0x0a, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x72, 0x6f,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f,
	0x67, 0x69, 0x63, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67,
	0x69, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f,
	0x73, 0x58, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x50, 0x6f,
	0x73, 0x59, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x5a, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x50, 0x6f, 0x73, 0x5a, 0x22, 0xa1, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x50, 0x6f,
	0x73, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x5a, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x5a, 0x22, 0x3a, 0x0a, 0x0c, 0x4c, 0x6f,
	0x67, 0x69, 0x63, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0a, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64,
	0x22, 0x3a, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x98, 0x01, 0x0a,
	0x12, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x46, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x26, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x55, 0x0a, 0x0f, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6e,
	0x67, 0x79, 0x6f, 0x75, 0x2f, 0x63, 0x65, 0x6c, 0x6c, 0x32, 0x2f, 0x5f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x6d, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_proto_rawDescOnce sync.Once
	file_protos_proto_rawDescData = file_protos_proto_rawDesc
)

func file_protos_proto_rawDescGZIP() []byte {
	file_protos_proto_rawDescOnce.Do(func() {
		file_protos_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_proto_rawDescData)
	})
	return file_protos_proto_rawDescData
}

var file_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_protos_proto_goTypes = []interface{}{
	(*ChatHello)(nil),            // 0: messages.ChatHello
	(*ChatHelloRet)(nil),         // 1: messages.ChatHelloRet
	(*NormalAck)(nil),            // 2: messages.NormalAck
	(*DBAuth)(nil),               // 3: messages.DBAuth
	(*DBAuthAck)(nil),            // 4: messages.DBAuthAck
	(*DBLoadPlayer)(nil),         // 5: messages.DBLoadPlayer
	(*DBLoadPlayerAck)(nil),      // 6: messages.DBLoadPlayerAck
	(*DBSavePlayer)(nil),         // 7: messages.DBSavePlayer
	(*DBRedisInit)(nil),          // 8: messages.DBRedisInit
	(*CenterReqLogin)(nil),       // 9: messages.CenterReqLogin
	(*CenterReqLoginAck)(nil),    // 10: messages.CenterReqLoginAck
	(*CenterOnSessionClose)(nil), // 11: messages.CenterOnSessionClose
	(*OnLogicLogined)(nil),       // 12: messages.OnLogicLogined
	(*OnLogicReOnline)(nil),      // 13: messages.OnLogicReOnline
	(*ReqLogout)(nil),            // 14: messages.ReqLogout
	(*OnLogout)(nil),             // 15: messages.OnLogout
	(*LogicLoadPlayer)(nil),      // 16: messages.LogicLoadPlayer
	(*ReqOffline)(nil),           // 17: messages.ReqOffline
	(*OnLeaveScene)(nil),         // 18: messages.OnLeaveScene
	(*OnOffline)(nil),            // 19: messages.OnOffline
	(*OnReOnline)(nil),           // 20: messages.OnReOnline
	(*ReqSwitchLine)(nil),        // 21: messages.ReqSwitchLine
	(*OnSwitchLineEnd)(nil),      // 22: messages.OnSwitchLineEnd
	(*LogicReqSwitchLine)(nil),   // 23: messages.LogicReqSwitchLine
	(*OnFightResult)(nil),        // 24: messages.OnFightResult
	(*TestSave)(nil),             // 25: messages.TestSave
	(*SMAllocScene)(nil),         // 26: messages.SMAllocScene
	(*SMAllocSceneAck)(nil),      // 27: messages.SMAllocSceneAck
	(*SMQueryScenes)(nil),        // 28: messages.SMQueryScenes
	(*SMAckScenes)(nil),          // 29: messages.SMAckScenes
	(*SMReqSceneByCfgId)(nil),    // 30: messages.SMReqSceneByCfgId
	(*SMQueryScene)(nil),         // 31: messages.SMQueryScene
	(*SMQuerySceneAck)(nil),      // 32: messages.SMQuerySceneAck
	(*SMRefresh)(nil),            // 33: messages.SMRefresh
	(*SMOnSceneEnd)(nil),         // 34: messages.SMOnSceneEnd
	(*SAllocScene)(nil),          // 35: messages.SAllocScene
	(*SceneEnter)(nil),           // 36: messages.SceneEnter
	(*ChangeScene)(nil),          // 37: messages.ChangeScene
	(*LogicOffline)(nil),         // 38: messages.LogicOffline
	(*SceneLeave)(nil),           // 39: messages.SceneLeave
	(*CheckPlayer2)(nil),         // 40: messages.CheckPlayer2
	(*SceneInitCardFight)(nil),   // 41: messages.SceneInitCardFight
	(*SceneCardResult)(nil),      // 42: messages.SceneCardResult
	(*PlayerInfo)(nil),           // 43: messages.PlayerInfo
	(*cproto.CharCard)(nil),      // 44: cproto.CharCard
}
var file_protos_proto_depIdxs = []int32{
	43, // 0: messages.DBLoadPlayerAck.Info:type_name -> messages.PlayerInfo
	43, // 1: messages.DBSavePlayer.Info:type_name -> messages.PlayerInfo
	43, // 2: messages.TestSave.Info:type_name -> messages.PlayerInfo
	44, // 3: messages.SceneInitCardFight.Cards:type_name -> cproto.CharCard
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_proto_init() }
func file_protos_proto_init() {
	if File_protos_proto != nil {
		return
	}
	file_playerinfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatHelloRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBAuthAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBLoadPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBLoadPlayerAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBSavePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBRedisInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CenterReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CenterReqLoginAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CenterOnSessionClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnLogicLogined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnLogicReOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicLoadPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnLeaveScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnReOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSwitchLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnSwitchLineEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicReqSwitchLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnFightResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestSave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMAllocScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMAllocSceneAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMQueryScenes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMAckScenes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMReqSceneByCfgId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMQueryScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMQuerySceneAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMRefresh); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMOnSceneEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAllocScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneEnter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogicOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[40].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPlayer2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[41].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneInitCardFight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_proto_msgTypes[42].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneCardResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_proto_goTypes,
		DependencyIndexes: file_protos_proto_depIdxs,
		MessageInfos:      file_protos_proto_msgTypes,
	}.Build()
	File_protos_proto = out.File
	file_protos_proto_rawDesc = nil
	file_protos_proto_goTypes = nil
	file_protos_proto_depIdxs = nil
}
