// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.0--rc1
// source: testmsg.proto

package msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"` //
	ReqId  int32  `protobuf:"varint,2,opt,name=ReqId,proto3" json:"ReqId,omitempty"`  // 请求id
	Type   string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`     // 数据类型
	Body   []byte `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`     // 序列化数据
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_testmsg_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ServiceRequest) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *ServiceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ServiceRequest1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"` //
	Type   string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`     // 数据类型
	ReqId  int32  `protobuf:"varint,3,opt,name=ReqId,proto3" json:"ReqId,omitempty"`  // 请求id
	Body   []byte `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`     // 序列化数据
}

func (x *ServiceRequest1) Reset() {
	*x = ServiceRequest1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest1) ProtoMessage() {}

func (x *ServiceRequest1) ProtoReflect() protoreflect.Message {
	mi := &file_testmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest1.ProtoReflect.Descriptor instead.
func (*ServiceRequest1) Descriptor() ([]byte, []int) {
	return file_testmsg_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRequest1) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ServiceRequest1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceRequest1) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *ServiceRequest1) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ServiceRequest2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId  int32  `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`  // 请求id
	Sender string `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"` //
	Type   string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`     // 数据类型
	Body   []byte `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`     // 序列化数据
}

func (x *ServiceRequest2) Reset() {
	*x = ServiceRequest2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest2) ProtoMessage() {}

func (x *ServiceRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_testmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest2.ProtoReflect.Descriptor instead.
func (*ServiceRequest2) Descriptor() ([]byte, []int) {
	return file_testmsg_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRequest2) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *ServiceRequest2) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ServiceRequest2) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceRequest2) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId   int32  `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`        // 数据类型
	Body    []byte `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`        // 序列化数据
	ErrCode int32  `protobuf:"varint,4,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"` // 0 - succ
	ErrInfo string `protobuf:"bytes,5,opt,name=ErrInfo,proto3" json:"ErrInfo,omitempty"`  // 错误信息
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_testmsg_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceResponse) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *ServiceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServiceResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *ServiceResponse) GetErrInfo() string {
	if x != nil {
		return x.ErrInfo
	}
	return ""
}

// 用于单元测试
type TestHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int32  `protobuf:"varint,1,opt,name=I,proto3" json:"I,omitempty"`
	S string `protobuf:"bytes,2,opt,name=S,proto3" json:"S,omitempty"`
}

func (x *TestHello) Reset() {
	*x = TestHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHello) ProtoMessage() {}

func (x *TestHello) ProtoReflect() protoreflect.Message {
	mi := &file_testmsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHello.ProtoReflect.Descriptor instead.
func (*TestHello) Descriptor() ([]byte, []int) {
	return file_testmsg_proto_rawDescGZIP(), []int{4}
}

func (x *TestHello) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *TestHello) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_testmsg_proto protoreflect.FileDescriptor

var file_testmsg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x66,
	0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x67, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x42,
	0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22,
	0x67, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x52, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x71,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x45, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x27,
	0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x49,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x49, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x53, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6e, 0x67, 0x79, 0x6f, 0x75, 0x2f, 0x63, 0x65,
	0x6c, 0x6c, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73,
	0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testmsg_proto_rawDescOnce sync.Once
	file_testmsg_proto_rawDescData = file_testmsg_proto_rawDesc
)

func file_testmsg_proto_rawDescGZIP() []byte {
	file_testmsg_proto_rawDescOnce.Do(func() {
		file_testmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_testmsg_proto_rawDescData)
	})
	return file_testmsg_proto_rawDescData
}

var file_testmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_testmsg_proto_goTypes = []interface{}{
	(*ServiceRequest)(nil),  // 0: prototestmsgs.ServiceRequest
	(*ServiceRequest1)(nil), // 1: prototestmsgs.ServiceRequest1
	(*ServiceRequest2)(nil), // 2: prototestmsgs.ServiceRequest2
	(*ServiceResponse)(nil), // 3: prototestmsgs.ServiceResponse
	(*TestHello)(nil),       // 4: prototestmsgs.TestHello
}
var file_testmsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testmsg_proto_init() }
func file_testmsg_proto_init() {
	if File_testmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testmsg_proto_goTypes,
		DependencyIndexes: file_testmsg_proto_depIdxs,
		MessageInfos:      file_testmsg_proto_msgTypes,
	}.Build()
	File_testmsg_proto = out.File
	file_testmsg_proto_rawDesc = nil
	file_testmsg_proto_goTypes = nil
	file_testmsg_proto_depIdxs = nil
}
